// <auto-generated />
using Employee.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Employee.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250311111333_empTable")]
    partial class empTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Employee.Models.Emp", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("departmentId")
                        .HasColumnType("int");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("salary")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Emps");

                    b.HasData(
                        new
                        {
                            id = 1,
                            city = "New York",
                            departmentId = 1,
                            gender = "male",
                            mobile = "1234567890",
                            name = "John",
                            salary = 50000
                        },
                        new
                        {
                            id = 2,
                            city = "Los Angeles",
                            departmentId = 2,
                            gender = "male",
                            mobile = "1234567890",
                            name = "Smith",
                            salary = 60000
                        },
                        new
                        {
                            id = 3,
                            city = "Mumbai",
                            departmentId = 3,
                            gender = "male",
                            mobile = "1234567890",
                            name = "Ravi",
                            salary = 70000
                        },
                        new
                        {
                            id = 4,
                            city = "Pune",
                            departmentId = 4,
                            gender = "female",
                            mobile = "1234567890",
                            name = "Kavita",
                            salary = 80000
                        });
                });

            modelBuilder.Entity("Employee.Models.department", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("departments");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "HR"
                        },
                        new
                        {
                            id = 2,
                            name = "IT"
                        },
                        new
                        {
                            id = 3,
                            name = "Finance"
                        },
                        new
                        {
                            id = 4,
                            name = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
